# version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/todo
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=hellothisissecret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:
